#!/usr/bin/env bash
# Generated by preconfig 0.1.0 from preconfig.yaml. Edit preconfig.yaml, not this file.
# Sets up orders-api on Ubuntu 24.04: python 3.12, postgres 16.
#
# Usage: bash .preconfig/setup.sh [all|machine|services|project|ready] ...
#   all       machine, services and project, in that order (the default)
#   machine   system packages, runtimes, tools and services; needs root or sudo
#   services  starts the services and creates the database user
#   project   the setup commands, run in the repository's root folder
#   ready     the ready check, run in the repository's root folder
#
# cloud-init and the Cursor Dockerfile run these same steps, and so does
# preconfig verify on a clean machine. Agents that take a setup script, such as
# Codex, Jules or Claude Code's cloud environments, can run this file too.
set -Eeuo pipefail

export DEBIAN_FRONTEND=noninteractive

if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
elif command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
else
  echo "preconfig: run this script as root, or install sudo" >&2
  exit 1
fi

CURRENT="start"
step() { CURRENT="$*"; printf '>>> preconfig: %s\n' "$*"; }
fail() { printf '>>> preconfig: FAILED: %s\n' "$*" >&2; exit 1; }
as_root() { if [ -n "$SUDO" ]; then "$SUDO" "$@"; else "$@"; fi; }
apt_install() { as_root apt-get install -y --no-install-recommends "$@"; }
systemd_running() { [ -d /run/systemd/system ]; }
on_error() { local rc=$?; trap - ERR; printf '>>> preconfig: FAILED: %s (exit code %s)\n' "$CURRENT" "$rc" >&2; exit "$rc"; }
trap on_error ERR

# The project's environment. Secrets are not here: set them in the environment
# that runs this script.
project_env() {
  export DATABASE_URL=postgres://orders:orders@localhost:5432/orders
  export REDIS_URL=redis://localhost:6379/0
}

machine() {
  step "machine 1/4: system packages"
  as_root apt-get update
  apt_install ca-certificates curl git gnupg
  step "machine 2/4: python 3.12"
  apt_install python3 python3-venv python3-pip
  python3 -c 'import sys; sys.exit(sys.version_info[:2] != (3, 12))' || fail "python3 is $(python3 --version 2>&1), not 3.12"
  step "machine 3/4: postgres 16"
  apt_install postgresql-16 postgresql-client-16
  /usr/lib/postgresql/16/bin/postgres --version | grep -q ' 16\.' || fail "postgres 16 did not install"
  step "machine 4/4: environment for login shells"
  as_root tee /etc/profile.d/preconfig.sh >/dev/null <<'PRECONFIG_ENV'
export DATABASE_URL=postgres://orders:orders@localhost:5432/orders
export REDIS_URL=redis://localhost:6379/0
PRECONFIG_ENV
  step "machine: done (python $(python3 -c 'import platform; print(platform.python_version())'), postgres $(/usr/lib/postgresql/16/bin/postgres --version | awk '{print $3}'))"
}

services() {
  step "services 1/1: postgres 16"
  if systemd_running; then
    as_root systemctl enable --now postgresql
  elif ! as_root pg_ctlcluster 16 main status >/dev/null 2>&1; then
    as_root pg_ctlcluster 16 main start
  fi
  for _ in $(seq 1 30); do pg_isready -q -h localhost -p 5432 && break; sleep 1; done
  pg_isready -q -h localhost -p 5432 || fail "postgres 16 is not accepting connections on localhost:5432"
  as_root runuser -u postgres -- psql -q -v ON_ERROR_STOP=1 -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'orders') THEN CREATE ROLE orders LOGIN PASSWORD 'orders'; ELSE ALTER ROLE orders WITH LOGIN PASSWORD 'orders'; END IF; END \$\$;"
  if [ "$(as_root runuser -u postgres -- psql -tAc "SELECT 1 FROM pg_database WHERE datname = 'orders'")" != "1" ]; then
    as_root runuser -u postgres -- createdb -O orders orders
  fi
  step "services: done"
  STARTED=1
}

project() {
  project_env
  [ -n "$STARTED" ] || services
  [ -n "${PAYMENTS_API_KEY:-}" ] || printf '>>> preconfig: warning: PAYMENTS_API_KEY is not set\n' >&2
  step "project 1/2: python3 -m venv .venv"
  python3 -m venv .venv
  step "project 2/2: .venv/bin/pip install -r requirements.txt"
  .venv/bin/pip install -r requirements.txt
}

ready() {
  project_env
  [ -n "$STARTED" ] || services
  step "ready 1/1: .venv/bin/pytest -q"
  .venv/bin/pytest -q
  step "ready: passed"
}

usage() {
  echo "usage: bash .preconfig/setup.sh [all|machine|services|project|ready] ..."
}

STARTED=""
[ $# -gt 0 ] || set -- all
for phase in "$@"; do
  case "$phase" in
    all) machine; services; project ;;
    machine|services|project|ready) "$phase" ;;
    -h|--help|help) usage; exit 0 ;;
    *) echo "preconfig: unknown step \"$phase\"" >&2; usage >&2; exit 2 ;;
  esac
done
