#!/usr/bin/env bash
# Generated by preconfig 0.1.0 from preconfig.yaml. Edit preconfig.yaml, not this file.
# Sets up web-shop on Ubuntu 24.04: node 22, pnpm@10, postgres 17.
#
# Usage: bash .preconfig/setup.sh [all|machine|services|project|ready] ...
#   all       machine, services and project, in that order (the default)
#   machine   system packages, runtimes, tools and services; needs root or sudo
#   services  starts the services and creates the database user
#   project   the setup commands, run in the repository's root folder
#   ready     the ready check, run in the repository's root folder
#
# cloud-init and the Cursor Dockerfile run these same steps, and so does
# preconfig verify on a clean machine. Agents that take a setup script, such as
# Codex, Jules or Claude Code's cloud environments, can run this file too.
set -Eeuo pipefail

export DEBIAN_FRONTEND=noninteractive

if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
elif command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
else
  echo "preconfig: run this script as root, or install sudo" >&2
  exit 1
fi

CURRENT="start"
step() { CURRENT="$*"; printf '>>> preconfig: %s\n' "$*"; }
fail() { printf '>>> preconfig: FAILED: %s\n' "$*" >&2; exit 1; }
as_root() { if [ -n "$SUDO" ]; then "$SUDO" "$@"; else "$@"; fi; }
apt_install() { as_root apt-get install -y --no-install-recommends "$@"; }
systemd_running() { [ -d /run/systemd/system ]; }
on_error() { local rc=$?; trap - ERR; printf '>>> preconfig: FAILED: %s (exit code %s)\n' "$CURRENT" "$rc" >&2; exit "$rc"; }
trap on_error ERR

# The project's environment. Secrets are not here: set them in the environment
# that runs this script.
project_env() {
  export DATABASE_URL=postgres://shop:shop@localhost:5432/shop
}

machine() {
  step "machine 1/5: system packages"
  as_root apt-get update
  apt_install ca-certificates curl git gnupg
  step "machine 2/5: node 22"
  if ! node --version 2>/dev/null | grep -q '^v22\.'; then
    as_root install -d -m 0755 /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | as_root gpg --dearmor --yes -o /etc/apt/keyrings/nodesource.gpg
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" | as_root tee /etc/apt/sources.list.d/nodesource.list >/dev/null
    as_root apt-get update
    apt_install nodejs
  fi
  node --version | grep -q '^v22\.' || fail "node is $(node --version), not 22"
  step "machine 3/5: pnpm@10"
  as_root npm install -g pnpm@10
  pnpm --version
  step "machine 4/5: postgres 17"
  as_root install -d /usr/share/postgresql-common/pgdg
  curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | as_root tee /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc >/dev/null
  echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt noble-pgdg main" | as_root tee /etc/apt/sources.list.d/pgdg.list >/dev/null
  as_root apt-get update
  apt_install postgresql-17 postgresql-client-17
  /usr/lib/postgresql/17/bin/postgres --version | grep -q ' 17\.' || fail "postgres 17 did not install"
  step "machine 5/5: environment for login shells"
  as_root tee /etc/profile.d/preconfig.sh >/dev/null <<'PRECONFIG_ENV'
export DATABASE_URL=postgres://shop:shop@localhost:5432/shop
PRECONFIG_ENV
  step "machine: done (node $(node --version | tr -d v), postgres $(/usr/lib/postgresql/17/bin/postgres --version | awk '{print $3}'))"
}

services() {
  step "services 1/1: postgres 17"
  if systemd_running; then
    as_root systemctl enable --now postgresql
  elif ! as_root pg_ctlcluster 17 main status >/dev/null 2>&1; then
    as_root pg_ctlcluster 17 main start
  fi
  for _ in $(seq 1 30); do pg_isready -q -h localhost -p 5432 && break; sleep 1; done
  pg_isready -q -h localhost -p 5432 || fail "postgres 17 is not accepting connections on localhost:5432"
  as_root runuser -u postgres -- psql -q -v ON_ERROR_STOP=1 -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'shop') THEN CREATE ROLE shop LOGIN PASSWORD 'shop'; ELSE ALTER ROLE shop WITH LOGIN PASSWORD 'shop'; END IF; END \$\$;"
  if [ "$(as_root runuser -u postgres -- psql -tAc "SELECT 1 FROM pg_database WHERE datname = 'shop'")" != "1" ]; then
    as_root runuser -u postgres -- createdb -O shop shop
  fi
  step "services: done"
  STARTED=1
}

project() {
  project_env
  [ -n "$STARTED" ] || services
  [ -n "${SESSION_SECRET:-}" ] || printf '>>> preconfig: warning: SESSION_SECRET is not set\n' >&2
  [ -n "${STRIPE_API_KEY:-}" ] || printf '>>> preconfig: warning: STRIPE_API_KEY is not set\n' >&2
  step "project 1/1: pnpm install --frozen-lockfile"
  pnpm install --frozen-lockfile
}

ready() {
  project_env
  [ -n "$STARTED" ] || services
  step "ready 1/1: pnpm test"
  pnpm test
  step "ready: passed"
}

usage() {
  echo "usage: bash .preconfig/setup.sh [all|machine|services|project|ready] ..."
}

STARTED=""
[ $# -gt 0 ] || set -- all
for phase in "$@"; do
  case "$phase" in
    all) machine; services; project ;;
    machine|services|project|ready) "$phase" ;;
    -h|--help|help) usage; exit 0 ;;
    *) echo "preconfig: unknown step \"$phase\"" >&2; usage >&2; exit 2 ;;
  esac
done
