#!/usr/bin/env bash
# Generated by preconfig 0.1.0 from preconfig.yaml. Edit preconfig.yaml, not this file.
# Sets up ingest-worker on Ubuntu 24.04: go 1.25, redis 8.
#
# Usage: bash .preconfig/setup.sh [all|machine|services|project|ready] ...
#   all       machine, services and project, in that order (the default)
#   machine   system packages, runtimes, tools and services; needs root or sudo
#   services  starts the services and creates the database user
#   project   the setup commands, run in the repository's root folder
#   ready     the ready check, run in the repository's root folder
#
# cloud-init and the Cursor Dockerfile run these same steps, and so does
# preconfig verify on a clean machine. Agents that take a setup script, such as
# Codex, Jules or Claude Code's cloud environments, can run this file too.
set -Eeuo pipefail

export DEBIAN_FRONTEND=noninteractive

if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
elif command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
else
  echo "preconfig: run this script as root, or install sudo" >&2
  exit 1
fi

CURRENT="start"
step() { CURRENT="$*"; printf '>>> preconfig: %s\n' "$*"; }
fail() { printf '>>> preconfig: FAILED: %s\n' "$*" >&2; exit 1; }
as_root() { if [ -n "$SUDO" ]; then "$SUDO" "$@"; else "$@"; fi; }
apt_install() { as_root apt-get install -y --no-install-recommends "$@"; }
systemd_running() { [ -d /run/systemd/system ]; }
on_error() { local rc=$?; trap - ERR; printf '>>> preconfig: FAILED: %s (exit code %s)\n' "$CURRENT" "$rc" >&2; exit "$rc"; }
trap on_error ERR

# The project's environment. Secrets are not here: set them in the environment
# that runs this script.
project_env() {
  export GOTOOLCHAIN=go1.25.0+auto
  export REDIS_URL=redis://localhost:6379/0
}

machine() {
  step "machine 1/4: system packages"
  as_root apt-get update
  apt_install ca-certificates curl git gnupg
  step "machine 2/4: go 1.25"
  apt_install golang-go
  export GOTOOLCHAIN=go1.25.0+auto
  go version | grep -q ' go1\.25[. ]' || fail "go is $(go version), not 1.25"
  step "machine 3/4: redis 8"
  as_root install -d -m 0755 /etc/apt/keyrings
  curl -fsSL https://packages.redis.io/gpg | as_root gpg --dearmor --yes -o /etc/apt/keyrings/redis.gpg
  echo "deb [signed-by=/etc/apt/keyrings/redis.gpg] https://packages.redis.io/deb noble main" | as_root tee /etc/apt/sources.list.d/redis.list >/dev/null
  as_root apt-get update
  apt_install redis-server redis-tools
  redis-server --version | grep -q ' v=8\.' || fail "redis-server is not version 8: $(redis-server --version)"
  step "machine 4/4: environment for login shells"
  as_root tee /etc/profile.d/preconfig.sh >/dev/null <<'PRECONFIG_ENV'
export GOTOOLCHAIN=go1.25.0+auto
export REDIS_URL=redis://localhost:6379/0
PRECONFIG_ENV
  step "machine: done (go $(go env GOVERSION | sed 's/^go//'), redis $(redis-server --version | sed 's/.* v=\([^ ]*\).*/\1/'))"
}

services() {
  step "services 1/1: redis 8"
  if systemd_running; then
    as_root systemctl enable --now redis-server
  elif ! redis-cli -h 127.0.0.1 ping >/dev/null 2>&1; then
    as_root install -d -o redis -g redis /run/redis
    as_root redis-server /etc/redis/redis.conf --daemonize yes
  fi
  for _ in $(seq 1 30); do [ "$(redis-cli -h 127.0.0.1 ping 2>/dev/null)" = "PONG" ] && break; sleep 1; done
  [ "$(redis-cli -h 127.0.0.1 ping 2>/dev/null)" = "PONG" ] || fail "redis 8 is not answering on localhost:6379"
  step "services: done"
  STARTED=1
}

project() {
  project_env
  [ -n "$STARTED" ] || services
  [ -n "${INGEST_TOKEN:-}" ] || printf '>>> preconfig: warning: INGEST_TOKEN is not set\n' >&2
  step "project 1/1: go mod download"
  go mod download
}

ready() {
  project_env
  [ -n "$STARTED" ] || services
  step "ready 1/1: go test ./..."
  go test ./...
  step "ready: passed"
}

usage() {
  echo "usage: bash .preconfig/setup.sh [all|machine|services|project|ready] ..."
}

STARTED=""
[ $# -gt 0 ] || set -- all
for phase in "$@"; do
  case "$phase" in
    all) machine; services; project ;;
    machine|services|project|ready) "$phase" ;;
    -h|--help|help) usage; exit 0 ;;
    *) echo "preconfig: unknown step \"$phase\"" >&2; usage >&2; exit 2 ;;
  esac
done
